"""Initial schema

Revision ID: 264b46e9514a
Revises: 
Create Date: 2026-06-19 18:45:19.016355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264b46e9514a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('time_of_day', sa.String(length=50), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_backup_date', sa.DateTime(), nullable=True),
    sa.Column('next_backup_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_name', sa.String(length=50), nullable=False),
    sa.Column('cycle_day', sa.Integer(), nullable=False),
    sa.Column('cycle_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discount_name', sa.String(length=50), nullable=False),
    sa.Column('discount_rate', sa.Float(), nullable=False),
    sa.Column('discount_type', sa.String(length=50), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('discount_description', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eap_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('eap_method', sa.String(length=20), nullable=False),
    sa.Column('ca_cert_path', sa.String(length=255), nullable=True),
    sa.Column('server_cert_path', sa.String(length=255), nullable=True),
    sa.Column('server_key_path', sa.String(length=255), nullable=True),
    sa.Column('client_cert_path', sa.String(length=255), nullable=True),
    sa.Column('client_key_path', sa.String(length=255), nullable=True),
    sa.Column('phase2_method', sa.String(length=20), nullable=True),
    sa.Column('inner_identity', sa.String(length=255), nullable=True),
    sa.Column('outer_identity', sa.String(length=255), nullable=True),
    sa.Column('config_blob', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('isps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('subscription_plan', sa.String(length=50), nullable=True),
    sa.Column('max_devices', sa.Integer(), nullable=True),
    sa.Column('max_customers', sa.Integer(), nullable=True),
    sa.Column('api_key', sa.String(length=100), nullable=False),
    sa.Column('radius_secret', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ldap_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('use_ssl', sa.Boolean(), nullable=True),
    sa.Column('use_tls', sa.Boolean(), nullable=True),
    sa.Column('bind_dn', sa.String(length=255), nullable=False),
    sa.Column('bind_password', sa.String(length=255), nullable=False),
    sa.Column('base_dn', sa.String(length=255), nullable=False),
    sa.Column('user_search_base', sa.String(length=255), nullable=True),
    sa.Column('user_search_filter', sa.String(length=255), nullable=True),
    sa.Column('group_search_base', sa.String(length=255), nullable=True),
    sa.Column('group_search_filter', sa.String(length=255), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radius_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('auth_port', sa.Integer(), nullable=True),
    sa.Column('acct_port', sa.Integer(), nullable=True),
    sa.Column('nas_type', sa.String(length=50), nullable=True),
    sa.Column('shortname', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radius_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snmp_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('snmp_version', sa.String(length=10), nullable=True),
    sa.Column('community', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('auth_protocol', sa.String(length=20), nullable=True),
    sa.Column('auth_key', sa.String(length=255), nullable=True),
    sa.Column('priv_protocol', sa.String(length=20), nullable=True),
    sa.Column('priv_key', sa.String(length=255), nullable=True),
    sa.Column('context_name', sa.String(length=100), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_poll', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_name', sa.String(length=50), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('tax_description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vpn_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('vpn_type', sa.String(length=20), nullable=False),
    sa.Column('config_blob', sa.Text(), nullable=False),
    sa.Column('server_public_key', sa.String(length=255), nullable=True),
    sa.Column('server_private_key', sa.String(length=255), nullable=True),
    sa.Column('server_endpoint', sa.String(length=255), nullable=True),
    sa.Column('server_port', sa.Integer(), nullable=True),
    sa.Column('allowed_ips', sa.String(length=255), nullable=True),
    sa.Column('dns_servers', sa.String(length=255), nullable=True),
    sa.Column('mtu', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('network_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isp_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('network_range', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['isp_id'], ['isps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radgroupcheck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupname', sa.String(length=64), nullable=False),
    sa.Column('attribute', sa.String(length=64), nullable=False),
    sa.Column('op', sa.String(length=2), nullable=False),
    sa.Column('value', sa.String(length=253), nullable=False),
    sa.Column('isp_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['isp_id'], ['isps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('radgroupcheck', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_radgroupcheck_groupname'), ['groupname'], unique=False)

    op.create_table('radgroupreply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupname', sa.String(length=64), nullable=False),
    sa.Column('attribute', sa.String(length=64), nullable=False),
    sa.Column('op', sa.String(length=2), nullable=False),
    sa.Column('value', sa.String(length=253), nullable=False),
    sa.Column('isp_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['isp_id'], ['isps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('radgroupreply', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_radgroupreply_groupname'), ['groupname'], unique=False)

    op.create_table('radius_user_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('groupname', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['radius_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('speed', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('popular', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('isp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['isp_id'], ['isps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snmp_poll_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snmp_device_id', sa.Integer(), nullable=False),
    sa.Column('oid', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=20), nullable=True),
    sa.Column('poll_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['snmp_device_id'], ['snmp_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_login', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('isp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['isp_id'], ['isps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vpn_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('vpn_config_id', sa.Integer(), nullable=False),
    sa.Column('client_public_key', sa.String(length=255), nullable=True),
    sa.Column('client_private_key', sa.String(length=255), nullable=True),
    sa.Column('client_ip', sa.String(length=50), nullable=True),
    sa.Column('config_blob', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_connected', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['vpn_config_id'], ['vpn_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'PENDING', name='customer_status'), nullable=False),
    sa.Column('join_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('package', sa.String(length=50), nullable=False),
    sa.Column('usage_percentage', sa.Integer(), nullable=True),
    sa.Column('device_count', sa.Integer(), nullable=True),
    sa.Column('last_payment_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('service_plan_id', sa.Integer(), nullable=True),
    sa.Column('isp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['isp_id'], ['isps.id'], ),
    sa.ForeignKeyConstraint(['service_plan_id'], ['service_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mikrotik_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.String(length=50), nullable=False),
    sa.Column('api_port', sa.Integer(), nullable=True),
    sa.Column('device_name', sa.String(length=50), nullable=False),
    sa.Column('device_ip', sa.String(length=50), nullable=False),
    sa.Column('device_model', sa.String(length=50), nullable=False),
    sa.Column('device_status', sa.Enum('ONLINE', 'OFFLINE', 'MAINTENANCE', 'DECOMMISSIONED', name='device_status'), nullable=False),
    sa.Column('uptime', sa.Integer(), nullable=True),
    sa.Column('client_count', sa.Integer(), nullable=True),
    sa.Column('bandwidth_usage', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('isp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['isp_id'], ['isps.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['network_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('network_infrastructure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=50), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('device_model', sa.String(length=50), nullable=False),
    sa.Column('device_serial_number', sa.String(length=50), nullable=False),
    sa.Column('device_ip_address', sa.String(length=50), nullable=False),
    sa.Column('device_mac_address', sa.String(length=50), nullable=False),
    sa.Column('device_location', sa.String(length=50), nullable=False),
    sa.Column('device_status', sa.Enum('ACTIVE', 'OFFLINE', 'MAINTENANCE', 'DECOMMISSIONED', name='infrastructure_status'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('warranty_expiry', sa.DateTime(), nullable=True),
    sa.Column('last_maintenance', sa.DateTime(), nullable=True),
    sa.Column('next_maintenance', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['network_zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_serial_number')
    )
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('log_message', sa.Text(), nullable=False),
    sa.Column('log_level', sa.String(length=50), nullable=False),
    sa.Column('log_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=50), nullable=False),
    sa.Column('device_mac_address', sa.String(length=50), nullable=False),
    sa.Column('device_ip_address', sa.String(length=50), nullable=False),
    sa.Column('device_model', sa.String(length=50), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_mac_address')
    )
    op.create_table('customer_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('note_type', sa.Enum('GENERAL', 'BILLING', 'TECHNICAL', 'SUPPORT', name='customer_note_type'), nullable=False),
    sa.Column('note_title', sa.String(length=255), nullable=True),
    sa.Column('note_content', sa.Text(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'OVERDUE', 'CANCELLED', name='invoice_status'), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('isp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['isp_id'], ['isps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='notification_priority'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radacct',
    sa.Column('radacctid', sa.BigInteger(), nullable=False),
    sa.Column('acctsessionid', sa.String(length=64), nullable=False),
    sa.Column('acctuniqueid', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('groupname', sa.String(length=64), nullable=True),
    sa.Column('realm', sa.String(length=64), nullable=True),
    sa.Column('nasipaddress', sa.String(length=15), nullable=False),
    sa.Column('nasportid', sa.String(length=15), nullable=True),
    sa.Column('nasporttype', sa.String(length=32), nullable=True),
    sa.Column('acctstarttime', sa.DateTime(), nullable=True),
    sa.Column('acctupdatetime', sa.DateTime(), nullable=True),
    sa.Column('acctstoptime', sa.DateTime(), nullable=True),
    sa.Column('acctinterval', sa.Integer(), nullable=True),
    sa.Column('acctsessiontime', sa.Integer(), nullable=True),
    sa.Column('acctauthentic', sa.String(length=32), nullable=True),
    sa.Column('connectinfo_start', sa.String(length=50), nullable=True),
    sa.Column('connectinfo_stop', sa.String(length=50), nullable=True),
    sa.Column('acctinputoctets', sa.BigInteger(), nullable=True),
    sa.Column('acctoutputoctets', sa.BigInteger(), nullable=True),
    sa.Column('calledstationid', sa.String(length=50), nullable=True),
    sa.Column('callingstationid', sa.String(length=50), nullable=True),
    sa.Column('acctterminatecause', sa.String(length=32), nullable=True),
    sa.Column('servicetype', sa.String(length=32), nullable=True),
    sa.Column('framedprotocol', sa.String(length=32), nullable=True),
    sa.Column('framedipaddress', sa.String(length=15), nullable=True),
    sa.Column('framedipv6address', sa.String(length=45), nullable=True),
    sa.Column('framedipv6prefix', sa.String(length=45), nullable=True),
    sa.Column('framedinterfaceid', sa.String(length=44), nullable=True),
    sa.Column('delegatedipv6prefix', sa.String(length=45), nullable=True),
    sa.Column('isp_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('mikrotik_device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['isp_id'], ['isps.id'], ),
    sa.ForeignKeyConstraint(['mikrotik_device_id'], ['mikrotik_devices.id'], ),
    sa.PrimaryKeyConstraint('radacctid')
    )
    with op.batch_alter_table('radacct', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_radacct_acctsessionid'), ['acctsessionid'], unique=False)
        batch_op.create_index(batch_op.f('ix_radacct_acctsessiontime'), ['acctsessiontime'], unique=False)
        batch_op.create_index(batch_op.f('ix_radacct_acctstarttime'), ['acctstarttime'], unique=False)
        batch_op.create_index(batch_op.f('ix_radacct_acctstoptime'), ['acctstoptime'], unique=False)
        batch_op.create_index(batch_op.f('ix_radacct_acctuniqueid'), ['acctuniqueid'], unique=False)
        batch_op.create_index(batch_op.f('ix_radacct_framedipaddress'), ['framedipaddress'], unique=False)
        batch_op.create_index(batch_op.f('ix_radacct_nasipaddress'), ['nasipaddress'], unique=False)
        batch_op.create_index(batch_op.f('ix_radacct_username'), ['username'], unique=False)

    op.create_table('radcheck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('attribute', sa.String(length=64), nullable=False),
    sa.Column('op', sa.String(length=2), nullable=False),
    sa.Column('value', sa.String(length=253), nullable=False),
    sa.Column('isp_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['isp_id'], ['isps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('radcheck', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_radcheck_username'), ['username'], unique=False)

    op.create_table('radius_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('attribute_name', sa.String(length=50), nullable=False),
    sa.Column('op', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radius_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('attribute', sa.String(length=50), nullable=False),
    sa.Column('op', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radius_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isp_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('mikrotik_device_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('session_start', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('session_end', sa.DateTime(), nullable=True),
    sa.Column('bytes_in', sa.BigInteger(), nullable=True),
    sa.Column('bytes_out', sa.BigInteger(), nullable=True),
    sa.Column('packets_in', sa.BigInteger(), nullable=True),
    sa.Column('packets_out', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['isp_id'], ['isps.id'], ),
    sa.ForeignKeyConstraint(['mikrotik_device_id'], ['mikrotik_devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('radreply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('attribute', sa.String(length=64), nullable=False),
    sa.Column('op', sa.String(length=2), nullable=False),
    sa.Column('value', sa.String(length=253), nullable=False),
    sa.Column('isp_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['isp_id'], ['isps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('radreply', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_radreply_username'), ['username'], unique=False)

    op.create_table('radusergroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('groupname', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('isp_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['isp_id'], ['isps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('radusergroup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_radusergroup_groupname'), ['groupname'], unique=False)
        batch_op.create_index(batch_op.f('ix_radusergroup_username'), ['username'], unique=False)

    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=50), nullable=False),
    sa.Column('ticket_subject', sa.String(length=255), nullable=False),
    sa.Column('ticket_description', sa.Text(), nullable=False),
    sa.Column('ticket_status', sa.Enum('OPEN', 'PENDING', 'RESOLVED', 'CLOSED', 'ON_HOLD', 'IN_PROGRESS', name='ticket_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticket_priority'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=50), nullable=True),
    sa.Column('resolved_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_number')
    )
    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_code', sa.String(length=50), nullable=False),
    sa.Column('voucher_type', sa.String(length=50), nullable=False),
    sa.Column('voucher_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('voucher_status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'USED', name='voucher_status'), nullable=False),
    sa.Column('used_by', sa.String(length=50), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('max_usage', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('used_by_customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['used_by_customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_code')
    )
    op.create_table('invoice_discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('discount_id', sa.Integer(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['discount_id'], ['discounts.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('transaction_id', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revenue_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revenue_date', sa.DateTime(), nullable=False),
    sa.Column('revenue_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('revenue_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_number', sa.String(length=50), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('transaction_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reference_id', sa.String(length=50), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('ticket_messages')
    op.drop_table('revenue_data')
    op.drop_table('payments')
    op.drop_table('invoice_items')
    op.drop_table('invoice_discounts')
    op.drop_table('vouchers')
    op.drop_table('tickets')
    with op.batch_alter_table('radusergroup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radusergroup_username'))
        batch_op.drop_index(batch_op.f('ix_radusergroup_groupname'))

    op.drop_table('radusergroup')
    with op.batch_alter_table('radreply', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radreply_username'))

    op.drop_table('radreply')
    op.drop_table('radius_sessions')
    op.drop_table('radius_replies')
    op.drop_table('radius_checks')
    with op.batch_alter_table('radcheck', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radcheck_username'))

    op.drop_table('radcheck')
    with op.batch_alter_table('radacct', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radacct_username'))
        batch_op.drop_index(batch_op.f('ix_radacct_nasipaddress'))
        batch_op.drop_index(batch_op.f('ix_radacct_framedipaddress'))
        batch_op.drop_index(batch_op.f('ix_radacct_acctuniqueid'))
        batch_op.drop_index(batch_op.f('ix_radacct_acctstoptime'))
        batch_op.drop_index(batch_op.f('ix_radacct_acctstarttime'))
        batch_op.drop_index(batch_op.f('ix_radacct_acctsessiontime'))
        batch_op.drop_index(batch_op.f('ix_radacct_acctsessionid'))

    op.drop_table('radacct')
    op.drop_table('notifications')
    op.drop_table('invoices')
    op.drop_table('customer_notes')
    op.drop_table('customer_documents')
    op.drop_table('customer_devices')
    op.drop_table('system_logs')
    op.drop_table('network_infrastructure')
    op.drop_table('mikrotik_devices')
    op.drop_table('customers')
    op.drop_table('audit_logs')
    op.drop_table('vpn_clients')
    op.drop_table('users')
    op.drop_table('snmp_poll_results')
    op.drop_table('service_plans')
    op.drop_table('radius_user_groups')
    with op.batch_alter_table('radgroupreply', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radgroupreply_groupname'))

    op.drop_table('radgroupreply')
    with op.batch_alter_table('radgroupcheck', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_radgroupcheck_groupname'))

    op.drop_table('radgroupcheck')
    op.drop_table('network_zones')
    op.drop_table('vpn_configs')
    op.drop_table('tax_rates')
    op.drop_table('system_settings')
    op.drop_table('snmp_devices')
    op.drop_table('radius_groups')
    op.drop_table('radius_clients')
    op.drop_table('ldap_servers')
    op.drop_table('isps')
    op.drop_table('eap_profiles')
    op.drop_table('discounts')
    op.drop_table('billing_cycles')
    op.drop_table('backup_schedules')
    # ### end Alembic commands ###
