[Interface]
PrivateKey = ALmGCVdv4yNz3a+ggmBQhG1HBUklmUV3ft3J0fNXfE0=
Address = 10.250.0.1/24
ListenPort = 51821

# mikrotik
[Peer]
PublicKey = ETpWfCdI2CazIO1/OJrfOz3THiUDHLzeHgS8TdNw/xM=
AllowedIPs = 10.250.0.2/32
